---
  #############################################################################
  ## CREST settings
  #############################################################################
  crest:
    # login server URL, uncomment the one you want
    #login_url: "https://sisilogin.testeveonline.com"  # singularity
    login_url: "https://login.eveonline.com"          # tranquility

    # CREST server URL
    #crest_url: "https://api-sisi.testeveonline.com/"  # singularity
    crest_url: "https://crest-tq.eveonline.com/"      # tranquility

    # Your app settings from https://developers.eveonline.com/ or https://developers.testeveonline.com/
    clientID: "9e68b690834a46e2adc3dcdf04613ec5"
    secretKey: "65LTBpPHlT76UEVxicNnu2et6tWfqhy1LohaH3zd"
    redirectUrl: "http://localhost:9021/callback"

  #############################################################################
  ## auth settings
  #############################################################################
  auth:
    # Run in alliance, corporation or public mode
    #mode: alliance
    #mode: corporation
    #mode: public

    domain: luv2.faith # domain you're running on
    # Pick your alliance or corporation
    alliance: Confederation of xXPIZZAXx
    corporation: Hard Knocks Inc.

    # Groups that users can sign up to or be in
    groups:
      # closed groups require admin-approval
      closed:
        - admin
        - ping
        - capital
        - timerboard
      # open groups can be joined by any internal/allied users
      open:
        - social
        - dota
      # public groups are the list of open groups that can be joined by random neutrals
      public:
        - dota
    graders:
      -
        type: "CrestKeyGrader"           # use this to validate CREST keys, uses your CREST config from above
      -
        type: "AlliancePilotGrader"       # mark all members of an alliance as Internal
        alliance: Play Hard Pray Harder   # uncomment this to run the plugin with an alliance that's not your configured one
      -
        type: "AlliedPilotGrader"        # used to mark blue pilots as Allies
        threshold: 4.9                   # the level of "blue" to require
        keyId: 1                         # a corp key with standings ticked to read the standings from
        vCode: whatever
        usealliance: true                # enable these to turn on corp or alliance standings, if both are on, alliance takes precedence
        usecorp: false

  #############################################################################
  ## embedded ldap settings
  #############################################################################
  embeddedldap:
    # folder to store the database in
    instancePath: ./ldap
    # port to run on
    port: 3389
    # base DN
    basedn: ou=pizza
    # host to bind to (leave this as localhost for security reasons unless you really know what you're doing)
    host: localhost